# Generated by Django 3.0.8 on 2021-04-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_auto_20210403_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkty',
            old_name='kategora',
            new_name='kategoria',
        ),
    ]
